import { Lock, Mail, Send } from 'lucide-react';
import { useState } from 'react';
import { Button } from '../components/Button';
import { Card } from '../components/Card';
import { SelectField } from '../components/FormControls';
import { PageShell } from '../components/PageShell';
import { SectionHeader } from '../components/SectionHeader';
import { pageMeta } from '../data/mockData';
import { api } from '../services/api';
import { trackMicroConversion, trackToolEngagement } from '../services/visitorIntelligence';

type QuoteForm = {
  name: string;
  travellers: string;
  destination: string;
  budget: string;
  dates: string;
  email: string;
  phone: string;
  specialRequests: string;
};

export function InternalQuoteGeneratorPage() {
  const [unlocked, setUnlocked] = useState(false);
  const [password, setPassword] = useState('');
  const [token, setToken] = useState('');
  const [sending, setSending] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [status, setStatus] = useState('');
  const [error, setError] = useState('');
  const [subject, setSubject] = useState('Your MyGlobalTrips quote');
  const [html, setHtml] = useState('');
  const [form, setForm] = useState<QuoteForm>({
    name: 'Riya Sharma',
    travellers: '2 adults',
    destination: 'Dubai + Maldives',
    budget: '$6,000 - $8,000',
    dates: '12-18 September 2026',
    email: 'riya@example.com',
    phone: '+971 58 556 6036',
    specialRequests: 'Overwater villa and private transfers',
  });

  async function generateEmail() {
    setGenerating(true);
    setError('');
    setStatus('');

    try {
      const response = await api.quoteEmail({
        travellerName: form.name,
        destination: form.destination,
        dates: form.dates,
        travellerCount: form.travellers,
        budget: form.budget,
        specialRequests: form.specialRequests,
        email: form.email,
        phone: form.phone,
      }, token);
      setSubject(response.subject);
      setHtml(response.html);
      setStatus('Quote email generated by backend.');
      trackToolEngagement('Quote email generated', { destination: form.destination, budget: form.budget });
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : 'Unable to generate quote email');
    } finally {
      setGenerating(false);
    }
  }

  async function sendEmail() {
    setSending(true);
    setError('');
    setStatus('');

    try {
      await api.sendEmail({
        to: form.email,
        subject,
        html,
      }, token);
      setStatus('Email sent successfully.');
      trackMicroConversion('Quote email sent', { destination: form.destination, email: form.email });
    } catch (requestError) {
      setError(requestError instanceof Error ? requestError.message : 'Unable to send email');
    } finally {
      setSending(false);
    }
  }

  if (!unlocked) {
    return (
      <PageShell>
        <section className="mx-auto grid min-h-[70vh] max-w-xl place-items-center px-4 pb-20 sm:px-6">
          <Card className="w-full p-7 text-center">
            <span className="mx-auto grid h-16 w-16 place-items-center rounded-full bg-gold text-navy">
              <Lock aria-hidden className="h-7 w-7" />
            </span>
            <h1 className="mt-6 font-display text-4xl font-bold">Internal quote desk</h1>
            <p className="mt-3 leading-7 text-mist">Enter the internal access password to access consultant tools.</p>
            <form
              className="mt-7 grid gap-4"
              onSubmit={(event) => {
                event.preventDefault();
                setError('');
                void api
                  .internalAuth({ password })
                  .then((response) => {
                    setToken(response.token);
                    setUnlocked(true);
                    setPassword('');
                  })
                  .catch((requestError) => {
                    setError(requestError instanceof Error ? requestError.message : 'Unable to unlock internal quote tools');
                  });
              }}
            >
              <input
                aria-label="Password"
                className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-center text-white"
                onChange={(event) => setPassword(event.target.value)}
                placeholder="Internal access password"
                type="password"
                value={password}
              />
              <Button type="submit">Unlock</Button>
              {error && <p className="rounded-[8px] border border-ruby/40 bg-ruby/20 px-4 py-3 text-sm text-[#ffb4cf]">{error}</p>}
            </form>
          </Card>
        </section>
      </PageShell>
    );
  }

  return (
    <PageShell>
      <section className="mx-auto max-w-7xl px-4 pb-20 sm:px-6 lg:px-8">
        <SectionHeader {...pageMeta.quote} align="center" />
        <div className="mt-10 grid gap-8 lg:grid-cols-[0.9fr_1.1fr]">
          <Card className="h-fit p-6">
            <div className="grid gap-5">
              <label className="grid gap-2 text-sm font-semibold text-white">
                Traveller name
                <input className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-white" onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} value={form.name} />
              </label>
              <label className="grid gap-2 text-sm font-semibold text-white">
                Traveller details
                <input className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-white" onChange={(event) => setForm((current) => ({ ...current, travellers: event.target.value }))} value={form.travellers} />
              </label>
              <label className="grid gap-2 text-sm font-semibold text-white">
                Client email
                <input className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-white" onChange={(event) => setForm((current) => ({ ...current, email: event.target.value }))} type="email" value={form.email} />
              </label>
              <label className="grid gap-2 text-sm font-semibold text-white">
                Phone
                <input className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-white" onChange={(event) => setForm((current) => ({ ...current, phone: event.target.value }))} value={form.phone} />
              </label>
              <SelectField label="Destination" value={form.destination} options={['Dubai + Maldives', 'Swiss Alps', 'Japan Golden Route', 'Paris & Riviera']} onChange={(destination) => setForm((current) => ({ ...current, destination }))} />
              <SelectField label="Budget" value={form.budget} options={['$3,000 - $5,000', '$6,000 - $8,000', '$10,000 - $15,000', '$20,000+']} onChange={(budget) => setForm((current) => ({ ...current, budget }))} />
              <label className="grid gap-2 text-sm font-semibold text-white">
                Dates
                <input className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-white" onChange={(event) => setForm((current) => ({ ...current, dates: event.target.value }))} value={form.dates} />
              </label>
              <label className="grid gap-2 text-sm font-semibold text-white">
                Special requests
                <textarea className="min-h-28 rounded-[8px] border border-white/14 bg-midnight/80 px-4 py-3 text-white" onChange={(event) => setForm((current) => ({ ...current, specialRequests: event.target.value }))} value={form.specialRequests} />
              </label>
              <Button disabled={generating} onClick={generateEmail}>
                {generating ? 'Generating...' : 'Generate backend email'}
              </Button>
              {status && <p className="rounded-[8px] border border-teal/40 bg-teal/20 px-4 py-3 text-sm text-[#7dd3c7]">{status}</p>}
              {error && <p className="rounded-[8px] border border-ruby/40 bg-ruby/20 px-4 py-3 text-sm text-[#ffb4cf]">{error}</p>}
            </div>
          </Card>

          <Card className="p-6">
            <div className="mb-5 flex items-center justify-between gap-4">
              <div className="flex items-center gap-3">
                <Mail aria-hidden className="h-6 w-6 text-gold" />
                <h2 className="font-display text-3xl font-bold">Editable email HTML</h2>
              </div>
              <Button disabled={sending || !html} onClick={sendEmail}>
                <Send aria-hidden className="h-4 w-4" />
                {sending ? 'Sending...' : 'Send'}
              </Button>
            </div>
            <label className="mb-4 grid gap-2 text-sm font-semibold text-white">
              Subject
              <input className="min-h-12 rounded-[8px] border border-white/14 bg-midnight/80 px-4 text-white" onChange={(event) => setSubject(event.target.value)} value={subject} />
            </label>
            <textarea
              aria-label="Editable quote email"
              className="min-h-[520px] w-full resize-none rounded-[8px] border border-white/14 bg-midnight/80 p-5 font-mono text-sm leading-7 text-mist outline-none focus:border-gold"
              onChange={(event) => setHtml(event.target.value)}
              placeholder="Generate an email to load backend HTML here."
              value={html}
            />
          </Card>
        </div>
      </section>
    </PageShell>
  );
}
